### ISSUE TITLE
everything brokey

### ISSUE THREAD

**Issue by joebiden234324425** [kingstefan26/cockmod-data#1]
everything in new version is broken and no unstuck feature for if u get stuck in a block

**Comment by kingstefan26** [comment]
explain brokey by giving examples
![icon](https://user-images.githubusercontent.com/70776766/148026538-c42cb36b-9f0d-4f4d-bbc3-01c269bfbc67.png)

**Comment by kingstefan26** [comment]
died rest in peace soldir
